services:
  duck-estimator:
    container_name: duck-estimator
    image: ghcr.io/bperel/duck-estimator
    env_file:
      - .env.prod.local
    environment:
      GIT_AUTHOR_NAME: Admin
      GIT_COMMITTER_NAME: Admin
      GIT_AUTHOR_EMAIL: admin@ducksmanager.net
      GIT_COMMITTER_EMAIL: admin@ducksmanager.net
    networks:
      - dm-server_db-network
    volumes:
      - cache:/home/cache
      - node_cache:/root/.cache
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro

networks:
  dm-server_db-network:
    external: true

volumes:
  cache:
  node_cache:
