services:
  duck-estimator:
    container_name: duck-estimator
    image: ghcr.io/bperel/duck-estimator
    environment:
      MYSQL_COA_HOST: db
      MYSQL_COA_PORT: 3306
      MYSQL_COA_DATABASE: coa
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      GIT_AUTHOR_NAME: Admin
      GIT_COMMITTER_NAME: Admin
      GIT_AUTHOR_EMAIL: admin@ducksmanager.net
      GIT_COMMITTER_EMAIL: admin@ducksmanager.net
    networks:
      - dm-server_db-network
    volumes:
      - cache:/home/cache
      - node_cache:/root/.cache
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro

networks:
  dm-server_db-network:
    external: true

volumes:
  cache:
  node_cache:
